export default {
    bHeader:true,
    bFooter:true,
    bLoading:false,
    home:[],
    new:[],
    reduce:[],
    car:[],
    product:[],
    productinfo:{},
    user:{
        auth:false,
        data:{"username":"kinoko57","password":"ly123"}
    },
    buycar:[
        {
            "id":"1",
            "content":"优质牛肉特价",
            "url":"/images/upload/goods007.jpg",
            "number":"1",
            "oldPrice":"28.99",
            "nowPrice":"23.29"
        }
    ]
}